
<!--- FORM -->
<?php 
    
    $url = "'" . $this->url('report',array('action'=>'runReport', 'date' => '')) . "'";
    //$calendar.= '<td class="calendar-day ' . $currentday . '" onclick="window.location.href='.$url.'">';

echo "<div class='form-group' style='width:250px;display:inline-flex;line-height: 53px;'>";
echo "<label>Mês/Ano</label>";
echo '<input type="text" name="datepicker-date-calendar" id="datepicker-date-calendar" 
        class="form-control" style="width:120px;display:inline-flex;top:5px;margin:5px"
        onchange="onChangeDateCalendar(this,' . $url . ')" value="' . $year . ' ' . $month . '"/>';
echo "</div>";

?>

<h3></h3>

<!--============= REPORT -->
<table class="table">

<tr>
    <th>Date</th>
    <th>Schedules</th>
    <th>Worked</th>
    <th>&nbsp;</th>
</tr>

<?php 

foreach ($points as $point) :

    echo "<tr>";
    echo "<td>";

    $formated_date = substr($point['date'], 6, 2) . "/";
    $formated_date.= substr($point['date'], 4, 2) . "/";
    $formated_date.= substr($point['date'], 0, 4);

    echo $formated_date;
    echo "</td>";

    echo '<td>';
    echo $this->escapeHtml($point['schedule']);
    echo "</td>";        
    echo '<td>';
    echo $this->escapeHtml($point['worked_hours_day']);
    echo "</td>";        
    echo '<td width="60%"></td>';

endforeach;

    echo "<tr><td></td>";
    echo "<td style='text-align:right'>Worked in " . $month_label . ": </td>";        
    echo '<td>';
    echo $worked_hours_month;
    echo "</td>";        
    echo '<td width="50%"></td>';
?>

</table>