<?php
// module/Point/view/point/point/delete.phtml:

$title = 'Delete point';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($point->date); ?>' by
    '<?php echo $this->escapeHtml($point->schedule); ?>'?
</p>
<?php
$url = $this->url('point', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $point->id; ?>" />
    <input type="submit" name="del" value="Yes"/>
    <input type="submit" name="del" value="No"/>
</div>
</form>