<?php
// module/Point/view/point/point/index.phtml:
echo '<h2>'.$month_label.' '.$year.'</h2>';
?>
<div id="table_month_link">
    <ul>
        <li><a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0101'));?>">
                <?php echo date("F", strtotime(date('Y').'01'.date('d'))) ?>
            </a>
        </li>|
         <li>
            <a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0201'));?>">
                <?php echo date("F", strtotime(date('Y').'02'.date('d'))) ?>
            </a>
        </li>|
        <li>
            <a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0301'));?>">
                <?php echo date("F", strtotime(date('Y').'03'.date('d'))) ?>
            </a>
        </li>|
        <li>
            <a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0401'));?>">
                <?php echo date("F", strtotime(date('Y').'04'.date('d'))) ?>
            </a>
        </li>|
        <li>
            <a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0501'));?>">
                <?php echo date("F", strtotime(date('Y').'05'.date('d'))) ?>
            </a>
        </li>|
        <li><a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0601'));?>">
                <?php echo date("F", strtotime(date('Y').'06'.date('d'))) ?>
            </a>
        </li>|
        <li>
            <a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0701'));?>">
                <?php echo date("F", strtotime(date('Y').'07'.date('d'))) ?>
            </a>
        </li>|
        <li><a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0801'));?>">
                <?php echo date("F", strtotime(date('Y').'08'.date('d'))) ?>
            </a>
        </li>|
        <li><a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'0901'));?>">
                <?php echo date("F", strtotime(date('Y').'09'.date('d'))) ?>
            </a>
        </li>|
        <li><a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'1001'));?>">
                <?php echo date("F", strtotime(date('Y').'10'.date('d'))) ?>
            </a>
        </li>|
        <li><a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'1101'));?>">
                <?php echo date("F", strtotime(date('Y').'11'.date('d'))) ?>
            </a>
        </li>|
        <li>
            <a href="<?php echo $this->url('point', array('action'=>'fetchByDay', 'date' => $year.'1201'));?>">
                <?php echo date("F", strtotime(date('Y').'12'.date('d'))) ?>
            </a>
        </li>
    </ul>
</div>
<?php

//==============DRAW CALENDAR===========


// Draw table for Calendar 
$calendar = '<table cellpadding="0" cellspacing="0" class="calendar">';

// Draw Calendar table headings 
$headings = array('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
$calendar.= '<tr class="calendar-row"><td class="calendar-day-head">'.implode('</td><td class="calendar-day-head">',$headings).'</td></tr>';

//days and weeks variable for now ... 
$running_day = date('w',mktime(0,0,0,$month,1,$year));
$days_in_month = date('t',mktime(0,0,0,$month,1,$year));
$days_in_this_week = 1;
$day_counter = 0;
$dates_array = array();

// row for week one 
$calendar.= '<tr class="calendar-row">';

// Display "blank" days until the first of the current week 
for($x = 0; $x < $running_day; $x++):
    $calendar.= '<td class="calendar-day-np">&nbsp;</td>';
    $days_in_this_week++;
endfor;

// Show days.... 
for($list_day = 1; $list_day <= $days_in_month; $list_day++):
    if($list_day==date('d') && $month==date('n'))
    {
        $currentday='currentday';
    }else
    {
        $currentday='';
    }
    $calendar.= '<td class="calendar-day '.$currentday.'">';
    
    // Add in the day number
    if( $list_day<=date('d') || $month < date('n'))
    {
        //$showtoday='<strong class="overday">' . $list_day . '</a></strong>';
        $showtoday='<strong class="overday">';
        //$showtoday.='<a href="point/fetchByDay/' . $list_day . '">' .  $list_day . '</a>';
        $day = $list_day < 10 ? '0' . $list_day : $list_day; 
        $showtoday.='<a href="'.$this->url('point',array('action'=>'fetchByDay', 'date' => $year.$month.$day)).'">'. $day .'</a>';
        //$showtoday.='<a href="'.$this->url('point',array('action'=>'edit', 'id' => 10)).'">'. $list_day .'</a>';
        $showtoday.='<strong>';

    }else
    {
        $showtoday=$list_day;
    }
    $calendar .= '<div class="day-number">'.$showtoday.'</div>';

    // Draw table end
    $calendar.= '</td>';
    if($running_day == 6):
        $calendar.= '</tr>';
        if(($day_counter+1) != $days_in_month):
            $calendar.= '<tr class="calendar-row">';
        endif;
        $running_day = -1;
        $days_in_this_week = 0;
    endif;
    $days_in_this_week++; $running_day++; $day_counter++;
endfor;

// Finish the rest of the days in the week
if($days_in_this_week < 8):
    for($x = 1; $x <= (8 - $days_in_this_week); $x++):
        $calendar.= '<td class="calendar-day-np">&nbsp;</td>';
    endfor;
endif;

// Draw table final row
$calendar.= '</tr>';

// Draw table end the table 
$calendar.= '</table>';

echo $calendar;

//==============END CALENDAR===========

?>

<h1></h1>
<p>
    <a href="<?php echo $this->url('point', array('action'=>'add'));?>">Add new point</a>
</p>

<table class="table">
<tr>
    <th>Date</th>
    <th>Schedule</th>
    <th>Sequence</th>
    <th>Note</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($points as $point) : ?>
<tr>
    <td><?php echo $this->escapeHtml(substr($point->date, 6, 2) . "/" . substr($point->date, 4, 2) . "/" . substr($point->date, 0, 4) );?></td>
    <td><?php echo $this->escapeHtml($point->schedule);?></td>
    <td><?php echo $this->escapeHtml($point->sequence);?></td>
    <td><?php echo $this->escapeHtml($point->note);?></td>
    <td>
        <a href="<?php echo $this->url('point',array('action'=>'edit', 'id' => $point->id));?>">Edit</a>
        <a href="<?php echo $this->url('point',array('action'=>'delete', 'id' => $point->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
