<div style="display:block">
    <div>
        <a href="<?php echo $this->url('point', array('action'=>'nextMonth'));?>">
            <img class="month_up" src="<?php echo $this->basePath('img/up.png') ?>" height="30" width="30">
        </a>
        <a href="<?php echo $this->url('point', array('action'=>'nextYear'));?>">
            <img class="year_up" src="<?php echo $this->basePath('img/up.png') ?>" height="30" width="30">
        </a>
    </div>
    <div><h2><?php echo $month_label.'    '.$year; ?></h2></div>
    <div>
        <a href="<?php echo $this->url('point', array('action'=>'previousMonth'));?>">
            <img class="month_down" src="<?php echo $this->basePath('img/down.png') ?>" height="30" width="30">
        </a>
        <a href="<?php echo $this->url('point', array('action'=>'previousYear'));?>">
            <img class="year_down" src="<?php echo $this->basePath('img/down.png') ?>" height="30" width="30">
        </a>
    </div>
</div>

<?php
//==============DRAW CALENDAR===========

// Draw table for Calendar 
$calendar = '<table cellpadding="0" cellspacing="0" class="calendar">';

// Draw Calendar table headings 
$headings = array('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
$calendar.= '<tr class="calendar-row"><td class="calendar-day-head">'.implode('</td><td class="calendar-day-head">',$headings).'</td></tr>';

//days and weeks variable for now ... 
$running_day = date('w',mktime(0,0,0,$month,1,$year));
$days_in_month = date('t',mktime(0,0,0,$month,1,$year));
$days_in_this_week = 1;
$day_counter = 0;
$dates_array = array();

// row for week one 
$calendar.= '<tr class="calendar-row">';

// Display "blank" days until the first of the current week 
for($x = 0; $x < $running_day; $x++):
    $calendar.= '<td class="calendar-day-np">&nbsp;</td>';
    $days_in_this_week++;
endfor;

// Show days.... 
for($list_day = 1; $list_day <= $days_in_month; $list_day++):
    if( $list_day==date('d') && $month==date('n') && $year==date('Y') )
    {
        $currentday='currentday';
    }else
    {
        //verifica se é o dia selecionado pelo usuário
        if( $list_day==$day ){
            $currentday='selected_day';
        }else{
            $currentday='';    
        }
    }

    
    
    // Add in the day number
    if( ($list_day <= date('d') && $month == date('n') && $year == date('Y')) ||
        ($year < date('Y')) || ($month < date('n') && $year == date('Y')))
    {
        //$showtoday='<strong class="overday">' . $list_day . '</a></strong>';
        $showtoday='<strong class="overday">';
        //$showtoday.='<a href="point/fetchByDay/' . $list_day . '">' .  $list_day . '</a>';
        $d = $list_day < 10 ? '0' . $list_day : $list_day; 
        $showtoday.=$d;
        //$showtoday.='<a href="'.$this->url('point',array('action'=>'edit', 'id' => 10)).'">'. $list_day .'</a>';
        $showtoday.='<strong>';

        $url = "'" . $this->url('point',array('action'=>'fetchByDay', 'date' => $year.$month.$d)) . "'";
        $calendar.= '<td class="calendar-day ' . $currentday . '" onclick="window.location.href='.$url.'">';

    }else
    {
        $showtoday=$list_day;
        $calendar.= '<td class="calendar-day ' . $currentday . '">';
    }

    $calendar .= '<div class="day-number" onclick="window.location=http://google.com">'.$showtoday.'</div>';

    // Draw table end
    $calendar.= '</td>';
    if($running_day == 6):
        $calendar.= '</tr>';
        if(($day_counter+1) != $days_in_month):
            $calendar.= '<tr class="calendar-row">';
        endif;
        $running_day = -1;
        $days_in_this_week = 0;
    endif;
    $days_in_this_week++; $running_day++; $day_counter++;
endfor;

// Finish the rest of the days in the week
if($days_in_this_week < 8):
    for($x = 1; $x <= (8 - $days_in_this_week); $x++):
        $calendar.= '<td class="calendar-day-np">&nbsp;</td>';
    endfor;
endif;

// Draw table final row
$calendar.= '</tr>';

// Draw table end the table 
$calendar.= '</table>';

echo $calendar;

//==============END CALENDAR===========

?>

<h3></h3>

<?php
    if (!($month > date('n') && $year >= date('Y'))){
?>
<p>
    <a href="<?php echo $this->url('point', array('action'=>'add'));?>">Add new point</a>
</p>
<?php
}
?>

<table class="table">
<tr>
    <th>Date</th>
    <th>Schedule</th>
    <th>Note</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($points as $point) : ?>
<tr>
    <td><?php echo $this->escapeHtml(substr($point->date, 6, 2) . "/" . substr($point->date, 4, 2) . "/" . substr($point->date, 0, 4) );?></td>
    <td width="30px"><?php echo $this->escapeHtml($point->schedule);?></td>
    <td width="80%"><?php echo $this->escapeHtml($point->note);?></td>
    <td width="120px">
        <a href="<?php echo $this->url('point',array('action'=>'edit', 'id' => $point->id));?>">Edit</a>
        <a href="<?php echo $this->url('point',array('action'=>'delete', 'id' => $point->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
