<?php
// module/Point/view/point/point/delete.phtml:

$title = 'Desmarcar dia não trabalhado';
$this->headTitle($title);
?>
<h4><?php echo $this->escapeHtml($title); ?></h4>

<p>Pretende prosseguir para desmarcar o dia 
    <?php echo $this->escapeHtml($formated_date); ?>?
</p>
<?php
$url = $this->url('day-not-worked', array(
    'action' => 'delete',
    'date'     => $this->date,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $day_not_worked->date; ?>" />
    <input type="submit" name="del" value="Sim" class="btn btn-primary"/>
    <input type="submit" name="del" value="Não" class="btn btn-warning"/>
</div>
</form>