<?php
// module/Point/view/point/point/mark-day-as-not-worked.phtml:

$title = 'Dias não trabalhados';
$this->headTitle($title);
?>
<h4><?php echo $this->escapeHtml($title); ?></h4>

<?php 
    
    $url = "'" . $this->url('day-not-worked',array('action'=>'fetchByMonth', 'date' => '')) . "'";
    echo "<div class='form-group' style='width:250px;display:inline-flex;line-height: 53px;'>";
    echo "<label>Mês/Ano</label>";
    echo '<input type="text" name="datepicker-date-calendar" id="datepicker-date-calendar" 
            class="form-control" style="width:120px;display:inline-flex;top:5px;margin:5px"
            onchange="onChangeDateCalendar(this,' . $url . ')" value="' . $year . ' ' . $month . '"/>';
    echo "</div>";

?>

<table class="table">

<tr>
    <th>Data</th>
    <th>Motivo</th>
    <th>Desmarcar</th>
</tr>

<?php 

foreach ($days_not_worked as $day_not_worked) :

    echo "<tr>";
    echo "<td>";

    $formated_date = substr($day_not_worked['date'], 6, 2) . "/";
    $formated_date.= substr($day_not_worked['date'], 4, 2) . "/";
    $formated_date.= substr($day_not_worked['date'], 0, 4);

    echo $formated_date;// . ' - '. $day_of_week;
    echo "</td>";

    echo '<td>';
    echo $this->escapeHtml($day_not_worked['reason']);    
    echo "</td>";        
    echo '<td>';
?>
    <a href="<?php echo $this->url('day-not-worked',array('action'=>'delete', 'date' => $day_not_worked['date']));?>">Desmarcar</a>
<?php
    echo "</td>";        

endforeach;
?>

</table>
<div style="display:inline-flex; line-height:33px; width:100%">
    <div style="display:inline-flex">
        <p>
            <a href="<?php echo $this->url('day-not-worked', array('action'=>'add', 'date' => $year . $month));?>">Adicionar</a>
        </p>
        &nbsp;
        |
        &nbsp;
        <p>
            <a href="<?php echo $this->url('point', array('action'=>'index'));?>">Voltar</a>
        </p>
        
    </div>
</div>

