<?php
// module/Point/view/point/point/mark-day-as-not-worked.phtml:
use Point\Model\Config;

$title = 'Configuração';
$this->headTitle($title);
?>
<h4><?php echo $this->escapeHtml($title); ?></h4>

<table class="table">

<tr>
    <th>Parâmetro</th>
    <th>Valor</th>
</tr>

<?php 

$url = $this->url('config',array('action'=>'edit'));

foreach ($configurations as $config) :
        echo "<tr>";
            echo '<form id="config_form" action="'. $url .'" method="post">';
            echo "<input type='hidden' name='id' value='" . $config['id'] . "' />";

            echo "<td>";
                echo '<input id="key" name="key" class="form-control" value="' . $config['_key'] . '" readonly="readonly"/>';
            echo "</td>";
            echo '<td>';
                if ( $config['_key'] == Config::JORNADA_SEMANAL ){
                    echo "<input type='checkbox' name='seg' value='1' " . (strpos($config['value'],'1') !== false ? "checked":"") . ">Segunda-Feira<br>";
                    echo "<input type='checkbox' name='ter' value='2' " . (strpos($config['value'],'2') !== false ? "checked":"") . ">Terça-Feira<br>";
                    echo "<input type='checkbox' name='qua' value='3' " . (strpos($config['value'],'3') !== false ? "checked":"") . ">Quarta-Feira<br>";
                    echo "<input type='checkbox' name='qui' value='4' " . (strpos($config['value'],'4') !== false ? "checked":"") . ">Quinta-Feira<br>";
                    echo "<input type='checkbox' name='sex' value='5' " . (strpos($config['value'],'5') !== false ? "checked":"") . ">Sexta-Feira<br>";
                    echo "<input type='checkbox' name='sab' value='6' " . (strpos($config['value'],'6') !== false ? "checked":"") . ">Sábado<br>";
                    echo "<input type='checkbox' name='dom' value='7' " . (strpos($config['value'],'7') !== false ? "checked":"") . ">Domingo<br>";
                }else{
                    echo '<input id="config_value" name="value" class="form-control" value="' . $config['value'] . '"/>';    
                }
            echo "</td>";        
            echo '<td>';
                echo '<input name="submit" type="submit" class="btn btn-warning" value="Salvar"/>';
            echo "</td>";  
            echo "</form>";
        echo "</tr>";        
endforeach;
?>

</table>

<div style="display:inline-flex; line-height:33px; width:100%">
    <div style="display:inline-flex">
        <p>
            <a href="<?php echo $this->url('point', array('action'=>'index'));?>">Voltar</a>
        </p>
    </div>
</div>

